---

- name: Check if Gnome Shell extension is already installed - {{ gnome_extension_info.name }}
  stat:
    path: "{{ ansible_user_dir }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
  register: r_gnome_extensions_check_existing

- name: Create temporary download directory
  tempfile:
    state: directory
    suffix: ".gnome_extension_download"
  register: r_gnome_extension_download_dir
  changed_when: no
  when: r_gnome_extensions_check_existing.stat.exists == False

- block:
    - name: Download Gnome Shell extension - {{ gnome_extension_info.name }}
      get_url:
        url: https://extensions.gnome.org{{ gnome_extension_info.download_url }}
        dest: "{{ r_gnome_extension_download_dir.path }}/{{ gnome_extension_info.uuid }}.zip"
      register: r_gnome_extension_download

    - name: Create install directory - {{ gnome_extension_info.name }}
      file:
        path: "{{ ansible_user_dir }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
        state: directory
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: 0775

    - name: Install Gnome Shell extension - {{ gnome_extension_info.name }}
      unarchive:
        src: "{{ r_gnome_extension_download.dest }}"
        dest: "{{ ansible_user_dir }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"

    - name: Enable Gnome Shell extension - {{ gnome_extension_info.name }}
      command: gnome-shell-extension-tool --enable-extension {{ gnome_extension_info.uuid }}
  always:
    - name: Delete temporary download directory
      file:
        path: "{{ r_gnome_extension_download_dir.path }}"
        state: absent
      changed_when: no
  when: r_gnome_extensions_check_existing.stat.exists == False
